bin/manage_variants: exit on build failure

diff --git a/bin/manage_variants b/bin/manage_variants
--- a/bin/manage_variants
+++ b/bin/manage_variants
@@ -25,4 +25,8 @@ while read -a toks; do
 
 	[[ "${oss}" =~ "${OS}" ]] || continue
 	"${buildblock}"  "${version}" --release=${release} "${dependencies[@]/#/--with=}"
+	if [[ $? != 0 ]]; then
+		echo "Failed building:  ${version} --release=${release} ${dependencies[@]/#/--with=}" 1>&2
+		exit 42
+	fi
 done < "${variants}"
