Simplify modulefile and chimerax script

diff --git a/EM/chimerax/chimerax b/EM/chimerax/chimerax
--- a/EM/chimerax/chimerax
+++ b/EM/chimerax/chimerax
@@ -1,8 +1,14 @@
 #!/bin/bash
 
-# Path to the Apptainer (Singularity) image
-IMAGE_DIR="$APPTAINER_IMAGE_DIR"
-IMAGE="$IMAGE_DIR/chimerax.sif"
+# Set UTF-8 locale
+export LANG=C.UTF-8
+export LC_ALL=C.UTF-8
+
+# Check if APPTAINER_IMAGE is set, exists, and is a .sif file
+if [[ -z "$APPTAINER_IMAGE" || ! -f "$APPTAINER_IMAGE" || "${APPTAINER_IMAGE##*.}" != "sif" ]]; then
+    echo "Error: Valid Apptainer (.sif) image not found. Please contact the system administrators."
+    exit 1
+fi
 
 # Execute ChimeraX inside the container
-singularity exec "$IMAGE" /usr/bin/chimerax "$@"
+singularity exec "$APPTAINER_IMAGE" /usr/bin/chimerax "$@"
